name: Get latest changes on main branch and merge into deploy branch

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
jobs:
  pull_changes_from_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main

    - name: Show list of file on actual directory
      run: ls

    - name: Configure git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
    - name: Merge main into deploy
      run: |
        git fetch origin
        git checkout deploy
        git merge origin/main -m "Merge main into deploy" --allow-unrelated-histories
        git push origin deploy --f
