name: Get latest changes on main branch and merge into deploy branch

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
jobs:
  pull_changes_from_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Show list of file on actual directory
      run: ls

    - name: Merge main -> deploy
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: main
        target_branch: deploy
        github_token: ${{ secrets.GITHUB_TOKEN }}
